on:
  issues:
    types:
      - opened
      - reopened

name: Create Issue In Jira

jobs:
  create_jira_issue:
    name: Create Jira Issue
    runs-on: ubuntu-latest
    steps:
    - name: Create Jira Issue
      uses: XeroAPI/Xero-NetStandard/.github/workflows/jira_create_issue.yml@master
