name: Create Issue in Jira

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  create_jira_issue:
    uses: XeroAPI/Xero-NetStandard/.github/workflows/jira_create_issue.yml@master
    secrets:
      envPAT: ${{ secrets.envPAT }}